package com.aria.reply;

import android.app.Notification;
import android.content.*;
import android.os.*;
import android.service.notification.*;
import android.text.TextUtils;
import android.app.RemoteInput;
import java.util.*;
import org.json.JSONObject;

public class AriaNotificationListener extends NotificationListenerService {
    public static final String WA = "com.whatsapp";
    private static final long DEFAULT_DELAY = 1800;
    private static AriaNotificationListener instance;
    private AriaStore store;
    private final Map<String, ArrayList<String>> burst = new HashMap<>();
    private final Map<String, Long> timers = new HashMap<>();
    private final Set<String> delivered = new HashSet<>();
    private Handler h;
    public static boolean live() { return instance != null; }

    @Override public void onCreate() { super.onCreate(); instance = this; store = new AriaStore(this); h = new Handler(Looper.getMainLooper()); }
    @Override public void onDestroy() { instance = null; super.onDestroy(); }

    @Override public void onNotificationPosted(StatusBarNotification sbn) {
        if (!WA.equals(sbn.getPackageName())) return;
        Notification n = sbn.getNotification();
        Bundle e = n.extras;
        String sender = e.getString(Notification.EXTRA_TITLE, "").trim();
        CharSequence raw = e.getCharSequence(Notification.EXTRA_TEXT);
        String text = raw == null ? "" : raw.toString().trim();
        if (sender.isEmpty() || text.isEmpty()) return;

        // WhatsApp notification summaries are metadata, never user messages.
        if (isSummary(text)) return;
        // Never capture our own WhatsApp replies or notifications generated by Aria.
        if (sender.equalsIgnoreCase("You") || sender.equalsIgnoreCase("Aria")) return;

        String contact = Contacts.resolve(this, sender);
        if (store.isRecentOutgoing(contact, text)) return;

        // Notification key + text prevents duplicate delivery while preserving identical messages from later notifications.
        String key = sbn.getKey() + "|" + text;
        synchronized (delivered) {
            if (delivered.contains(key)) return;
            delivered.add(key);
            if (delivered.size() > 300) delivered.clear();
        }

        store.addMessage(contact, "user", text);
        ArrayList<String> q = burst.computeIfAbsent(contact, k -> new ArrayList<>());
        q.add(text);

        if (timers.containsKey(contact)) h.removeCallbacksAndMessages(contact);
        Runnable job = () -> generate(contact);
        h.postAtTime(job, contact, SystemClock.uptimeMillis() + DEFAULT_DELAY);
        timers.put(contact, System.currentTimeMillis() + DEFAULT_DELAY);
        store.put("last_capture", contact + ": " + text);

        if (store.bool("hide_raw", false)) {
            try { cancelNotification(sbn.getKey()); } catch (Exception ignored) {}
        }
    }

    private boolean isSummary(String s) {
        String x = s.toLowerCase(Locale.US).trim();
        return x.matches(".*\\b\\d+\\s+(new\\s+)?messages?\\b.*") ||
               x.contains("notifications from") || x.equals("checking for new messages") ||
               x.equals("new message") || x.equals("new messages");
    }

    private void generate(String contact) {
        ArrayList<String> q = burst.remove(contact);
        timers.remove(contact);
        if (q == null || q.isEmpty()) return;

        String provider = store.get("provider", "Groq");
        SecurePrefs secure = new SecurePrefs(this);
        String key = secure.get(provider.equals("Gemini") ? "gemini_key" : "groq_key");
        String model = store.get(provider.equals("Gemini") ? "gemini_model" : "groq_model",
                provider.equals("Gemini") ? "gemini-2.0-flash" : "llama-3.1-8b-instant");
        String context = store.context(contact, 20);
        String user = String.join("\n", q);
        String system = "You are Aria, a concise WhatsApp assistant. Contact: " + contact +
                ". Only use this contact's context. Never expose another contact's messages. " +
                "Never claim you sent something unless the app actually sent it. " +
                "If a request is ambiguous, ask exactly what is needed before creating a follow-up. " +
                "If you commit to a future action, make that commitment explicit.\n" +
                "CONTEXT:\n" + context;

        AriaApi.call(provider, key, model, system, user, (ok, reply, error) -> {
            if (!ok) { store.put("last_error", error); return; }
            store.addMessage(contact, "assistant", reply);
            Notifications.summary(this, contact, reply, store);
            extractAction(contact, reply);
            if (store.bool("auto_reply", false)) sendToLatest(contact, reply);
        });
    }

    private void extractAction(String contact, String reply) {
        String x = reply.toLowerCase(Locale.US);
        boolean promise = x.contains("i'll") || x.contains("i will") || x.contains("i’ll") ||
                x.contains("i will inform") || x.contains("i'll inform") ||
                x.contains("bata dunga") || x.contains("inform kar dunga") ||
                x.contains("bhej dunga") || x.contains("remind") || x.contains("i'll tell");
        if (promise) {
            store.addAction(contact, "Aria follow-up", reply);
            Notifications.task(this, store);
        }
    }

    private void sendToLatest(String contact, String reply) {
        try {
            store.rememberOutgoing(contact, reply);
            for (StatusBarNotification s : getActiveNotifications()) {
                if (!WA.equals(s.getPackageName())) continue;
                Bundle e = s.getNotification().extras;
                String t = e.getString(Notification.EXTRA_TITLE, "");
                if (!Contacts.resolve(this, t).equals(contact)) continue;
                Notification.Action[] actions = s.getNotification().actions;
                if (actions == null) continue;
                for (Notification.Action a : actions) {
                    if (a.getRemoteInputs() != null && a.getRemoteInputs().length > 0) {
                        Intent i = new Intent();
                        Bundle results = new Bundle();
                        results.putCharSequence(
                            a.getRemoteInputs()[0].getResultKey(),
                            reply
                        );
                        RemoteInput.addResultsToIntent(
                            a.getRemoteInputs(),
                            i,
                            results
                        );
                        a.actionIntent.send(this, 0, i);
                        return;
                    }
                }
            }
        } catch (Exception e) { store.put("last_error", "Direct responder: " + e.getMessage()); }
    }
}
